[build]
target = ["x86_64-unknown-none"]
rustflags = [
    "-C", "relocation-model=dynamic-no-pic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--nmagic",
    # "-C", "link-arg=-no-pie",
    # "-C", "link-arg=-melf_i386",
]

# [unstable]
# build-std = ["core", "compiler_builtins"]
